-- Sample Medical Data for RAG System Testing

-- Insert sample patients
INSERT INTO patients (patient_id, first_name, last_name, date_of_birth, gender, contact_number, email, address, medical_history, allergies, current_medications, hospital_id) VALUES
('P001', 'John', 'Smith', '1985-03-15', 'Male', '+1-555-0101', 'john.smith@email.com', '123 Main St, City, State', 'Hypertension, Type 2 Diabetes', 'Penicillin, Sulfa drugs', 'Metformin 500mg twice daily, Lisinopril 10mg daily', 1),
('P002', 'Sarah', 'Johnson', '1990-07-22', 'Female', '+1-555-0102', 'sarah.johnson@email.com', '456 Oak Ave, City, State', 'Asthma, Seasonal allergies', 'Latex', 'Albuterol inhaler, Fluticasone nasal spray', 1),
('P003', 'Michael', 'Brown', '1978-11-08', 'Male', '+1-555-0103', 'michael.brown@email.com', '789 Pine Rd, City, State', 'Coronary artery disease, High cholesterol', 'None known', 'Atorvastatin 20mg daily, Aspirin 81mg daily', 2),
('P004', 'Emily', 'Davis', '1992-04-30', 'Female', '+1-555-0104', 'emily.davis@email.com', '321 Elm St, City, State', 'Migraine, Anxiety', 'Codeine', 'Sumatriptan 50mg as needed, Sertraline 50mg daily', 2),
('P005', 'David', 'Wilson', '1982-09-12', 'Male', '+1-555-0105', 'david.wilson@email.com', '654 Maple Dr, City, State', 'GERD, Sleep apnea', 'None known', 'Omeprazole 20mg daily, CPAP therapy', 3);

-- Insert sample medical records
INSERT INTO medical_records (patient_id, record_type, record_date, doctor_name, department, diagnosis, symptoms, treatment_plan, medications_prescribed, lab_results, notes) VALUES
(1, 'diagnosis', '2024-01-15', 'Dr. Anderson', 'Cardiology', 'Hypertension Stage 2', 'Elevated blood pressure readings, occasional headaches', 'Lifestyle modifications, medication management', 'Lisinopril 10mg daily, Amlodipine 5mg daily', 'BP: 160/95 mmHg, ECG: Normal sinus rhythm', 'Patient advised to reduce salt intake and exercise regularly'),
(1, 'lab_result', '2024-01-20', 'Dr. Anderson', 'Cardiology', 'Diabetes monitoring', 'Routine check', 'Continue current treatment', 'Metformin 500mg twice daily', 'HbA1c: 7.2%, Fasting glucose: 145 mg/dL', 'Blood sugar control improving but needs monitoring'),
(2, 'diagnosis', '2024-02-10', 'Dr. Martinez', 'Pulmonology', 'Asthma exacerbation', 'Wheezing, shortness of breath, chest tightness', 'Bronchodilator therapy, inhaled corticosteroids', 'Albuterol inhaler 2 puffs every 4-6 hours, Fluticasone 220mcg twice daily', 'Peak flow: 65% predicted, SpO2: 94%', 'Patient responded well to treatment'),
(3, 'diagnosis', '2024-01-25', 'Dr. Thompson', 'Cardiology', 'Coronary artery disease', 'Chest pain on exertion, fatigue', 'Medication management, cardiac rehabilitation', 'Atorvastatin 20mg daily, Aspirin 81mg daily, Metoprolol 25mg twice daily', 'Troponin: Normal, ECG: ST depression', 'Referred to cardiac rehabilitation program'),
(4, 'diagnosis', '2024-02-05', 'Dr. Garcia', 'Neurology', 'Migraine with aura', 'Severe headache, visual disturbances, nausea', 'Abortive and preventive therapy', 'Sumatriptan 50mg as needed, Propranolol 40mg twice daily', 'MRI brain: Normal, No structural abnormalities', 'Patient reports 3-4 migraine attacks per month'),
(5, 'diagnosis', '2024-01-30', 'Dr. Lee', 'Gastroenterology', 'GERD', 'Heartburn, acid reflux, chest discomfort', 'Lifestyle modifications, PPI therapy', 'Omeprazole 20mg daily, Ranitidine 150mg twice daily', 'Endoscopy: Mild esophagitis, No Barrett\'s esophagus', 'Advise to avoid spicy foods and eat smaller meals');

-- Insert medical knowledge base entries
INSERT INTO medical_knowledge_base (title, content_type, content, source, tags) VALUES
('Hypertension Management Guidelines', 'treatment', 'Hypertension is defined as blood pressure consistently above 140/90 mmHg. Treatment includes lifestyle modifications (diet, exercise, weight loss) and medication therapy. First-line medications include ACE inhibitors, ARBs, calcium channel blockers, and thiazide diuretics. Regular monitoring and patient education are essential for successful management.', 'American Heart Association Guidelines 2023', ARRAY['hypertension', 'cardiovascular', 'treatment', 'guidelines']),
('Diabetes Type 2 Treatment Protocol', 'treatment', 'Type 2 diabetes management focuses on glycemic control through diet, exercise, and medication. Metformin is typically the first-line medication. Additional agents include sulfonylureas, DPP-4 inhibitors, GLP-1 receptor agonists, and insulin. Regular HbA1c monitoring and complication screening are crucial.', 'American Diabetes Association Standards of Care 2024', ARRAY['diabetes', 'endocrinology', 'treatment', 'protocol']),
('Asthma Exacerbation Management', 'treatment', 'Asthma exacerbations require prompt treatment with short-acting beta agonists (SABA) and systemic corticosteroids. Severe exacerbations may require hospitalization. Prevention includes proper inhaler technique, trigger avoidance, and regular controller medication use. Peak flow monitoring helps assess control.', 'Global Initiative for Asthma (GINA) 2024', ARRAY['asthma', 'pulmonology', 'exacerbation', 'emergency']),
('Coronary Artery Disease Diagnosis', 'diagnosis', 'Coronary artery disease is diagnosed through clinical assessment, ECG, stress testing, and coronary angiography. Risk factors include hypertension, diabetes, smoking, and family history. Treatment includes lifestyle modifications, medications (statins, antiplatelets), and revascularization when indicated.', 'American College of Cardiology Guidelines', ARRAY['CAD', 'cardiology', 'diagnosis', 'coronary']),
('Migraine Treatment Options', 'treatment', 'Migraine treatment includes acute (abortive) and preventive therapies. Acute treatments include triptans, NSAIDs, and antiemetics. Preventive treatments include beta-blockers, anticonvulsants, and CGRP inhibitors. Lifestyle modifications and trigger identification are important components of management.', 'American Headache Society Guidelines', ARRAY['migraine', 'neurology', 'headache', 'treatment']),
('GERD Management Strategies', 'treatment', 'GERD management includes lifestyle modifications (diet, weight loss, elevation of head of bed), over-the-counter antacids, H2 blockers, and proton pump inhibitors. Severe cases may require surgical intervention. Long-term PPI use requires monitoring for potential side effects.', 'American Gastroenterological Association', ARRAY['GERD', 'gastroenterology', 'acid reflux', 'treatment']),
('Antibiotic Allergy Management', 'allergy', 'Penicillin allergy affects 10% of patients. True allergies are IgE-mediated and can cause anaphylaxis. Alternative antibiotics include cephalosporins (with caution), macrolides, and fluoroquinolones. Skin testing and desensitization may be options for confirmed allergies.', 'Infectious Diseases Society of America', ARRAY['allergy', 'penicillin', 'antibiotics', 'immunology']),
('Sleep Apnea Diagnosis and Treatment', 'diagnosis', 'Sleep apnea is diagnosed through sleep studies. Treatment options include CPAP therapy, oral appliances, and surgery. CPAP is the gold standard for moderate to severe cases. Lifestyle modifications include weight loss, positional therapy, and avoiding alcohol and sedatives.', 'American Academy of Sleep Medicine', ARRAY['sleep apnea', 'pulmonology', 'CPAP', 'sleep disorders']);

-- Insert federated dataset information
INSERT INTO federated_datasets (dataset_name, dataset_type, hospital_id, record_count, last_sync, is_active) VALUES
('Hospital 1 Patient Records', 'patient_data', 1, 1500, CURRENT_TIMESTAMP, true),
('Hospital 2 Patient Records', 'patient_data', 2, 1200, CURRENT_TIMESTAMP, true),
('Hospital 3 Patient Records', 'patient_data', 3, 1800, CURRENT_TIMESTAMP, true),
('Medical Knowledge Base', 'medical_knowledge', NULL, 500, CURRENT_TIMESTAMP, true),
('Clinical Trials Database', 'clinical_trials', NULL, 200, CURRENT_TIMESTAMP, true);
